<a href="https://colab.research.google.com/github/Abubakar919666/Python/blob/main/Data_Visualization_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [14]:
# Load and Display Data â†’ Read the dataset and print the first 5 rows.
data = pd.read_csv('covid_19_country_wise_latest.csv')
data.head()

,Unnamed: 0,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,0,Afghanistan,36263,1269,25198,9796,106.0,10.0,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,1,Albania,4880,144,2745,1991,117.0,6.0,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,2,Algeria,27973,1163,18837,7973,616.0,8.0,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,3,Andorra,907,52,803,52,10.0,0.0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,4,Angola,950,41,242,667,18.0,1.0,0,4.32,25.47,16.94,749,201,26.84,Africa

In [30]:
data.tail()

,Country/Region,Confirmed,Deaths,Recovered,Active,New_cases,New_deaths,New_recovered,Deaths_/_100_Cases,Recovered_/_100_Cases,Deaths_/_100_Recovered,Confirmed_last_week,1_week_change,1_week_%_increase,WHO_Region
index,,,,,,,,,,,,,,,
182,West Bank and Gaza,10621,78,3752,6791,152.0,2.0,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
183,Western Sahara,10,1,8,1,0.0,0.0,0,10.00,80.00,12.50,10,0,0.00,Africa
184,Yemen,1691,483,833,375,10.0,4.0,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71.0,1.0,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,non,542,2126,192.0,2.0,24,1.33,20.04,6.64,1713,991,57.85,Africa

In [15]:
# Set the Dataset index is Unnamed: 0
data.set_index("Unnamed: 0", inplace=True)
data.head()

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
Unnamed: 0,,,,,,,,,,,,,,,
0,Afghanistan,36263,1269,25198,9796,106.0,10.0,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117.0,6.0,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616.0,8.0,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10.0,0.0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18.0,1.0,0,4.32,25.47,16.94,749,201,26.84,Africa

In [16]:
# Now replace the index column Unnamed: 0 name with index
data.rename_axis("index", inplace=True)
data.head()

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
index,,,,,,,,,,,,,,,
0,Afghanistan,36263,1269,25198,9796,106.0,10.0,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117.0,6.0,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616.0,8.0,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10.0,0.0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18.0,1.0,0,4.32,25.47,16.94,749,201,26.84,Africa

In [17]:
# Function to replace whitespace in column names with underscores
def replace_whitespace(Data):

    # Replace whitespaces with underscores in column names
    data.columns = data.columns.str.replace(' ', '_')

    # Return the updated DataFrame
    return data


data = replace_whitespace(data)

data.head()

,Country/Region,Confirmed,Deaths,Recovered,Active,New_cases,New_deaths,New_recovered,Deaths_/_100_Cases,Recovered_/_100_Cases,Deaths_/_100_Recovered,Confirmed_last_week,1_week_change,1_week_%_increase,WHO_Region
index,,,,,,,,,,,,,,,
0,Afghanistan,36263,1269,25198,9796,106.0,10.0,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117.0,6.0,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616.0,8.0,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10.0,0.0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18.0,1.0,0,4.32,25.47,16.94,749,201,26.84,Africa

In [24]:
column_names = data.columns
print(column_names)

Index(['Country/Region', 'Confirmed', 'Deaths', 'Recovered', 'Active',
       'New_cases', 'New_deaths', 'New_recovered', 'Deaths_/_100_Cases',
       'Recovered_/_100_Cases', 'Deaths_/_100_Recovered',
       'Confirmed_last_week', '1_week_change', '1_week_%_increase',
       'WHO_Region'],
      dtype='object')

In [21]:
data_types = data.dtypes
print(data_types)

Country/Region             object
Confirmed                   int64
Deaths                     object
Recovered                   int64
Active                      int64
New_cases                 float64
New_deaths                float64
New_recovered               int64
Deaths_/_100_Cases        float64
Recovered_/_100_Cases     float64
Deaths_/_100_Recovered    float64
Confirmed_last_week         int64
1_week_change               int64
1_week_%_increase         float64
WHO_Region                 object
dtype: object

In [29]:
missing_values = data.isnull().sum()
print(missing_values)

Country/Region             0
Confirmed                  0
Deaths                     0
Recovered                  0
Active                     0
New_cases                 10
New_deaths                10
New_recovered              0
Deaths_/_100_Cases         0
Recovered_/_100_Cases      0
Deaths_/_100_Recovered     0
Confirmed_last_week        0
1_week_change              0
1_week_%_increase          0
WHO_Region                 0
dtype: int64

In [32]:
# fill the nan values with the mean of the column
data.fillna(data.mean())

TypeError: Could not convert ["AfghanistanAlbaniaAlgeriaAndorraAngolaAntigua and BarbudaArgentinaArmeniaAustraliaAustriaAzerbaijanBahamasBahrainBangladeshBarbadosBelarusBelgiumBelizeBeninBhutanBoliviaBosnia and HerzegovinaBotswanaBrazilBruneiBulgariaBurkina FasoBurmaBurundiCabo VerdeCambodiaCameroonCanadaCentral African RepublicChadChileChinaColombiaComorosCongo (Brazzaville)Congo (Kinshasa)Costa RicaCote d'IvoireCroatiaCubaCyprusCzechiaDenmarkDjiboutiDominicaDominican RepublicEcuadorEgyptEl SalvadorEquatorial GuineaEritreaEstoniaEswatiniEthiopiaFijiFinlandFranceGabonGambiaGeorgiaGermanyGhanaGreeceGreenlandGrenadaGuatemalaGuineaGuinea-BissauGuyanaHaitiHoly SeeHondurasHungaryIcelandIndiaIndonesiaIranIraqIrelandIsraelItalyJamaicaJapanJordanKazakhstanKenyaKosovoKuwaitKyrgyzstanLaosLatviaLebanonLesothoLiberiaLibyaLiechtensteinLithuaniaLuxembourgMadagascarMalawiMalaysiaMaldivesMaliMaltaMauritaniaMauritiusMexicoMoldovaMonacoMongoliaMontenegroMoroccoMozambiqueNamibiaNepalNetherlandsNew ZealandNicaraguaNigerNigeriaNorth MacedoniaNorwayOmanPakistanPanamaPapua New GuineaParaguayPeruPhilippinesPolandPortugalQatarRomaniaRussiaRwandaSaint Kitts and NevisSaint LuciaSaint Vincent and the GrenadinesSan MarinoSao Tome and PrincipeSaudi ArabiaSenegalSerbiaSeychellesSierra LeoneSingaporeSlovakiaSloveniaSomaliaSouth AfricaSouth KoreaSouth SudanSpainSri LankaSudanSurinameSwedenSwitzerlandSyriaTaiwan*TajikistanTanzaniaThailandTimor-LesteTogoTrinidad and TobagoTunisiaTurkeyUSUgandaUkraineUnited Arab EmiratesUnited KingdomUruguayUzbekistanVenezuelaVietnamWest Bank and GazaWestern SaharaYemenZambiaZimbabwe"] to numeric

In [33]:
# Fill NaN values with the mean for numeric columns only
data[data.select_dtypes(include=['number']).columns] = data.select_dtypes(include=['number']).fillna(data.mean())

# Check the updated dataset
print(data)

TypeError: Could not convert ["AfghanistanAlbaniaAlgeriaAndorraAngolaAntigua and BarbudaArgentinaArmeniaAustraliaAustriaAzerbaijanBahamasBahrainBangladeshBarbadosBelarusBelgiumBelizeBeninBhutanBoliviaBosnia and HerzegovinaBotswanaBrazilBruneiBulgariaBurkina FasoBurmaBurundiCabo VerdeCambodiaCameroonCanadaCentral African RepublicChadChileChinaColombiaComorosCongo (Brazzaville)Congo (Kinshasa)Costa RicaCote d'IvoireCroatiaCubaCyprusCzechiaDenmarkDjiboutiDominicaDominican RepublicEcuadorEgyptEl SalvadorEquatorial GuineaEritreaEstoniaEswatiniEthiopiaFijiFinlandFranceGabonGambiaGeorgiaGermanyGhanaGreeceGreenlandGrenadaGuatemalaGuineaGuinea-BissauGuyanaHaitiHoly SeeHondurasHungaryIcelandIndiaIndonesiaIranIraqIrelandIsraelItalyJamaicaJapanJordanKazakhstanKenyaKosovoKuwaitKyrgyzstanLaosLatviaLebanonLesothoLiberiaLibyaLiechtensteinLithuaniaLuxembourgMadagascarMalawiMalaysiaMaldivesMaliMaltaMauritaniaMauritiusMexicoMoldovaMonacoMongoliaMontenegroMoroccoMozambiqueNamibiaNepalNetherlandsNew ZealandNicaraguaNigerNigeriaNorth MacedoniaNorwayOmanPakistanPanamaPapua New GuineaParaguayPeruPhilippinesPolandPortugalQatarRomaniaRussiaRwandaSaint Kitts and NevisSaint LuciaSaint Vincent and the GrenadinesSan MarinoSao Tome and PrincipeSaudi ArabiaSenegalSerbiaSeychellesSierra LeoneSingaporeSlovakiaSloveniaSomaliaSouth AfricaSouth KoreaSouth SudanSpainSri LankaSudanSurinameSwedenSwitzerlandSyriaTaiwan*TajikistanTanzaniaThailandTimor-LesteTogoTrinidad and TobagoTunisiaTurkeyUSUgandaUkraineUnited Arab EmiratesUnited KingdomUruguayUzbekistanVenezuelaVietnamWest Bank and GazaWestern SaharaYemenZambiaZimbabwe"] to numeric

In [43]:
# Select only numeric columns
numeric_columns = data.select_dtypes(include=['number']).columns

# Fill NaN values in numeric columns with the mean
data.fillna(data[numeric_columns].mean())

# Check the updated dataset
print(data)

           Country/Region     Confirmed Deaths     Recovered        Active  \
index
0             Afghanistan  88130.935829   1269  50631.481283  34001.935829
1                 Albania  88130.935829    144  50631.481283  34001.935829
2                 Algeria  88130.935829   1163  50631.481283  34001.935829
3                 Andorra  88130.935829     52  50631.481283  34001.935829
4                  Angola  88130.935829     41  50631.481283  34001.935829
...                   ...           ...    ...           ...           ...
182    West Bank and Gaza  88130.935829     78  50631.481283  34001.935829
183        Western Sahara  88130.935829      1  50631.481283  34001.935829
184                 Yemen  88130.935829    483  50631.481283  34001.935829
185                Zambia  88130.935829    140  50631.481283  34001.935829
186              Zimbabwe  88130.935829    non  50631.481283  34001.935829

         New_cases  New_deaths  New_recovered  Deaths_/_100_Cases  \
index
0      1282.740113    30.40113     933.812834            3.019519
1      1282.740113    30.40113     933.812834            3.019519
2      1282.740113    30.40113     933.812834            3.019519
3      1282.740113    30.40113     933.812834            3.019519
4      1282.740113    30.40113     933.812834            3.019519
...            ...         ...            ...                 ...
182    1282.740113    30.40113     933.812834            3.019519
183    1282.740113    30.40113     933.812834            3.019519
184    1282.740113    30.40113     933.812834            3.019519
185    1282.740113    30.40113     933.812834            3.019519
186    1282.740113    30.40113     933.812834            3.019519

       Recovered_/_100_Cases  Deaths_/_100_Recovered  Confirmed_last_week  \
index
0                  64.820535                     inf         78682.475936
1                  64.820535                     inf         78682.475936
2                  64.820535                     inf         78682.475936
3                  64.820535                     inf         78682.475936
4                  64.820535                     inf         78682.475936
...                      ...                     ...                  ...
182                64.820535                     inf         78682.475936
183                64.820535                     inf         78682.475936
184                64.820535                     inf         78682.475936
185                64.820535                     inf         78682.475936
186                64.820535                     inf         78682.475936

       1_week_change  1_week_%_increase             WHO_Region
index
0        9448.459893          13.606203  Eastern Mediterranean
1        9448.459893          13.606203                 Europe
2        9448.459893          13.606203                 Africa
3        9448.459893          13.606203                 Europe
4        9448.459893          13.606203                 Africa
...              ...                ...                    ...
182      9448.459893          13.606203  Eastern Mediterranean
183      9448.459893          13.606203                 Africa
184      9448.459893          13.606203  Eastern Mediterranean
185      9448.459893          13.606203                 Africa
186      9448.459893          13.606203                 Africa

[187 rows x 15 columns]